# Generated by Django 4.1.3 on 2023-09-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportID', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=False)),
                ('report', models.JSONField(default=dict)),
            ],
        ),
    ]
