# Generated by Django 4.1.3 on 2023-09-26 13:20

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='businessHours',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='originalTimeFormat',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='schedule',
            field=models.JSONField(default=data.models.get_default_schedule),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='storeID',
            field=models.IntegerField(unique=True),
        ),
    ]
