# Generated by Django 4.1.3 on 2023-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_restaurants_businesshours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='extrapolated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='timeslice',
            name='timestamp',
            field=models.DateTimeField(unique=True),
        ),
    ]
