# Generated by Django 4.1.3 on 2023-09-29 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_status_extrapolated_alter_timeslice_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='storeID',
            new_name='store',
        ),
    ]
